name: Update Daily/Item list

on: push

jobs:
  run:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies & Start Program
      run: |
        dir
        chcp 65001
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python program.py
        dir
      env: 
        X_NAVER_CLIENT_ID: ${{ secrets.X_NAVER_CLIENT_ID }}
        X_NAVER_CLIENT_SECRET: ${{ secrets.X_NAVER_CLIENT_SECRET }}

        keyword0: "리모컨"
        keyword1: "모니터"
        keyword2: "마우스"
        keyword3: "프린터기"
        keyword4: "소파"
        keyword5: "TV"
        keyword6: "스피커"
        keyword7: "스탠드조명"
        keyword8: "테이블"
        keyword9: "슬리퍼"


    - name: Commit files
      id: commit
      run: |
        git config --local user.email "jklh0202@naver.com"
        git config --local user.name "jongwuner"
        git add --all
        if [-z "$(git status --porcelain)"]; then
           echo "::set-output name=push::false"
        else
           git commit -m "Add changes" -a
           echo "::set-output name=push::true"
        fi
      shell: bash
    - name: Push changes
      if: steps.commit.outputs.push == 'true'
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
